version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: cv-builder-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cv_builder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cv-builder-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cv-builder-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cv-builder-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  cv-builder-network:
    driver: bridge 