openapi: 3.0.3
info:
  title: CV Builder API
  description: API documentation for the CV Builder application
  version: 1.0.0
  contact:
    name: CV Builder Support
    url: https://github.com/Jimbo5289/cv-builder-2
servers:
  - url: http://localhost:3005
    description: Development server
  - url: https://cv-builder-backend-2jax.onrender.com
    description: Production server

tags:
  - name: Auth
    description: Authentication operations
  - name: CV
    description: CV management operations
  - name: User
    description: User management operations
  - name: Subscription
    description: Subscription management operations

paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                name:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
        '409':
          description: Email already exists

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
        '401':
          description: Invalid credentials

  /api/cv:
    get:
      tags:
        - CV
      summary: Get all CVs for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of CVs
        '401':
          description: Unauthorized
    post:
      tags:
        - CV
      summary: Create a new CV
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: CV created successfully
        '401':
          description: Unauthorized

  /api/cv/{id}:
    get:
      tags:
        - CV
      summary: Get a specific CV by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: CV details
        '404':
          description: CV not found
    put:
      tags:
        - CV
      summary: Update a CV
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: CV updated successfully
        '404':
          description: CV not found
    delete:
      tags:
        - CV
      summary: Delete a CV
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: CV deleted successfully
        '404':
          description: CV not found

  /api/subscription:
    get:
      tags:
        - Subscription
      summary: Get user's subscription status
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Subscription details
        '401':
          description: Unauthorized
    post:
      tags:
        - Subscription
      summary: Create a subscription
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - priceId
              properties:
                priceId:
                  type: string
      responses:
        '200':
          description: Subscription created successfully
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 