services:
  # Backend API service
  - type: web
    name: cv-builder-2
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
      - key: MOCK_DATABASE
        value: true
      - key: FRONTEND_URL
        value: https://cv-builder-2.onrender.com
      - key: SKIP_AUTH_CHECK
        value: false 